name: SwiftLint

on:
  pull_request:
    branches: [ main ]
    paths:
      - '**/*.swift'
      - '.swiftlint.yml'
  push:
    branches: [ main ]
    paths:
      - '**/*.swift'
      - '.swiftlint.yml'

jobs:
  swiftlint:
    runs-on: macos-latest
    
    steps:
    - name: Checkout
      uses: actions/checkout@v4
      
    - name: Install SwiftLint
      run: brew install swiftlint
      
    - name: Run SwiftLint
      run: |
        echo "Running SwiftLint..."
        swiftlint --reporter github-actions-logging
        
    - name: SwiftLint (Strict)
      run: |
        echo "Running SwiftLint with strict error checking..."
        # エラーレベルの違反があれば失敗させる
        swiftlint --strict --reporter github-actions-logging